### ISSUE TITLE
Add descriptions for README.md File

### ISSUE THREAD

**Issue by sgyyz** [sgyyz/git-test#1]
Please add descriptions for README.md file.

**Comment by sgyyz** [comment]
@sgyyz please help to do this task

**Comment by troyyoung** [comment]
I can help you to add the test. @sgyyz

**Comment by sgyyz** [comment]
@troyyoung go a head, expecting your hard work.

**Comment by sgyyz** [comment]
@troyyoung thank you for your hard work.
